const STORAGE_KEY='komorebi_bookings_v1';
const SLOTS=[{time:'17:30',label:'ディナー',capacity:8},{time:'19:00',label:'ディナー',capacity:6},{time:'20:30',label:'ディナー',capacity:0},{time:'21:00',label:'バー利用',capacity:10}];
const MENU=[{name:'季節野菜の前菜',text:'旬の野菜を中心に、軽く始められる盛り合わせです。',price:'¥1,280',image:'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=1000&q=80',alt:'前菜プレート'},{name:'グリルメイン',text:'肉料理または魚料理から選べる、ディナーの中心になる一皿です。',price:'¥2,600',image:'https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=1000&q=80',alt:'メイン料理のステーキ'},{name:'デザートセット',text:'食後のデザートとドリンクを組み合わせたセットです。',price:'¥980',image:'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=80',alt:'デザートとコーヒー'}];
const $=selector=>document.querySelector(selector);
const escapeHtml=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
function today(){return new Date().toISOString().slice(0,10)}
function loadBookings(){return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}
function saveBookings(items){localStorage.setItem(STORAGE_KEY,JSON.stringify(items))}
function bookingsFor(date){return loadBookings().filter(item=>item.date===date)}
function usedSeats(date,time){return bookingsFor(date).filter(item=>item.time===time).reduce((sum,item)=>sum+Number(item.party),0)}
function remaining(date,slot){return Math.max(0,slot.capacity-usedSeats(date,slot.time))}
function renderMenu(){document.querySelector('#menuRoot').innerHTML=MENU.map(item=>`<article class="menu-card"><img src="${item.image}" alt="${item.alt}"><div><h3>${item.name}</h3><p>${item.text}</p><span class="price">${item.price}</span></div></article>`).join('')}
function renderTimeOptions(date){const current=$('#timeSelect').value;$('#timeSelect').innerHTML='<option value="">選択してください</option>'+SLOTS.filter(slot=>remaining(date,slot)>0).map(slot=>`<option value="${slot.time}">${slot.time}（残り${remaining(date,slot)}席）</option>`).join('');if([...$('#timeSelect').options].some(option=>option.value===current))$('#timeSelect').value=current}
function renderSlots(){const date=$('#selectedDate').value;document.querySelector('#slotsRoot').innerHTML=SLOTS.map(slot=>{const rest=remaining(date,slot);const full=rest<=0;return `<article class="slot ${full?'full':''}"><span>${slot.label}</span><strong>${slot.time}</strong><span>${slot.capacity===0?'満席':`残り ${rest}席`}</span><button class="btn" data-time="${slot.time}" ${full?'disabled':''}>この時間で予約</button></article>`}).join('');document.querySelectorAll('[data-time]').forEach(button=>button.addEventListener('click',()=>{const time=button.dataset.time;$('#formDate').value=date;$('#timeSelect').value=time;$('#summary').textContent=`選択中の時間: ${date} ${time}`;document.getElementById('reservation').scrollIntoView({behavior:'smooth'})}));renderTimeOptions(date)}
function renderBookings(){const items=loadBookings();$('#bookingCount').textContent=`${items.length}件の予約`;$('#bookingList').innerHTML=items.length?items.map(item=>`<article class="booking-card"><div><h3>${escapeHtml(item.date)} ${escapeHtml(item.time)} / ${escapeHtml(item.party)}名</h3><p>${escapeHtml(item.name)}様 ${escapeHtml(item.tel)}</p><small>${escapeHtml(item.note||'ご要望なし')}</small></div><button class="btn secondary" data-cancel="${item.id}">キャンセル</button></article>`).join(''):'<p class="empty">まだ予約は保存されていません。</p>';document.querySelectorAll('[data-cancel]').forEach(button=>button.addEventListener('click',()=>{if(confirm('この予約をキャンセルしますか？')){saveBookings(loadBookings().filter(item=>item.id!==button.dataset.cancel));renderAll();$('#formStatus').textContent='予約をキャンセルしました。'}}))}
function renderAll(){renderSlots();renderBookings()}
function handleSubmit(event){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));const party=Number(data.party);const slot=SLOTS.find(item=>item.time===data.time);if(!slot){$('#formStatus').textContent='予約時間を選択してください。';return}const rest=remaining(data.date,slot);if(party>rest){$('#formStatus').textContent=`${data.time}の残席は${rest}席です。人数を変更してください。`;return}const booking={id:`RSV-${Date.now().toString().slice(-6)}`,...data,party,createdAt:new Date().toLocaleString('ja-JP')};saveBookings([booking,...loadBookings()]);event.currentTarget.reset();$('#selectedDate').value=data.date;$('#formDate').value=data.date;$('#summary').textContent='選択中の時間: 未選択';$('#formStatus').textContent=`${booking.name}様、${booking.date} ${booking.time} / ${booking.party}名の予約を保存しました。`;renderAll();location.hash='bookings'}
document.addEventListener('DOMContentLoaded',()=>{const date=today();$('#selectedDate').value=date;$('#formDate').value=date;renderMenu();renderAll();$('#selectedDate').addEventListener('change',()=>{$('#formDate').value=$('#selectedDate').value;renderAll()});$('#formDate').addEventListener('change',()=>{$('#selectedDate').value=$('#formDate').value;renderAll()});$('#timeSelect').addEventListener('change',()=>{$('#summary').textContent=`選択中の時間: ${$('#formDate').value} ${$('#timeSelect').value||'未選択'}`});$('#reservationForm').addEventListener('submit',handleSubmit);$('#resetBookings').addEventListener('click',()=>{if(confirm('保存された予約をすべて削除しますか？')){saveBookings([]);renderAll();$('#formStatus').textContent='予約データを初期化しました。'}})});
